### ISSUE TITLE
"贡献"tab页请求的头像资源是http的

### ISSUE THREAD

**Issue by JianmingXia** [mtdhb/mtdhb#100]
![image](https://user-images.githubusercontent.com/9691577/39681384-7a67197e-51dc-11e8-95bc-ebf874d291d7.png)

大图上不了，就贴个小图了

**Comment by zhuweiyou** [comment]
感谢反馈，现已修复 https://github.com/mtdhb/www/commit/54d8295c9ad7cb1acd851f661c0b1b04bf6e29c5

完全加载完页面，再刷新页面即可更新
