### ISSUE TITLE
[问题]cookies(ewxshinfo), 如何获取

### ISSUE THREAD

**Issue by abusemydnac** [mtdhb/mtdhb#103]
*旧版本 看起来无需微信cookies*

*对于新版本问题*
cookies增加了ewxshinfo,
抓包看了下,重新微信oauth2授权.

**Comment by abusemydnac** [comment]
关闭贡献了. TAT

**Comment by zhuweiyou** [comment]
ewxshinfo 的问题需要你自行分析，虽然关闭贡献了，但是旧的还在用。
