### ISSUE TITLE
[问题]ewxshinfo 加密方式?(小白自己写碰见的问题)

### ISSUE THREAD

**Issue by abusemydnac** [mtdhb/mtdhb#104]
[新来的不能贡献美团cookies]
仿照旧版写了下;[问题如下]

1. 相对于old代码,美团修改了  /async/coupon/sharechannelredirect 提交的参数 增加了,code,(code由WX oauth2 接口返回),放弃.

2. 回到问题1,上个封包  shareweixinsilent, 自行构造的 提交总是301 到 WX oauth2接口,放弃
3. 问题2中使用另外一种方式 shareweixinnew,自行构造的提交会返回 一段 cookies ewxshinfo,更新cookies提交返回7002 .[实际抓包返回 ewxshinfo,ewxinfo],

请问 ewxshinfo  ewxinfo 怎么构造的,我看了old代码中 只有ewxinfo ,而ewxshinfo没有,是类似的构造方式吗.

**Comment by abusemydnac** [comment]
ewxshinfo 加密方式与  ewxinfo 不同.
请教下,不同处是?key iv不同吗

**Comment by zhuweiyou** [comment]
`ewxshinfo` 是有效值

**Comment by zhuweiyou** [comment]
`ewxshinfo` 是有效值

**Comment by abusemydnac** [comment]
ewxshinfo   加密方式是? @zhuweiyou  美团不能贡献 只能自己写看看.一直卡在这个地方. thx~~~~

**Comment by zhuweiyou** [comment]
我又不是美团的，怎么会知道加密方式。。。
