### ISSUE TITLE
关于美团token的问题

### ISSUE THREAD

**Issue by JaonDong** [mtdhb/mtdhb#106]
我本来是使用C#来弄的，但是在生成token的时候受阻，抓包，查看美团是使用一个JS生成的。
我看了Old的代码也是从美团上down下来的。
1、想问下，这个token是需要那些信息创建的？
2、我看网站里说美团已经停止贡献了，美团是赢家了  是什么意思？

**Comment by JaonDong** [comment]
还有我发现手机号是和cookie绑定的。为啥网站说cookie和手机号无关。。

**Comment by zhuweiyou** [comment]
跟手机号没什么关系，如果你发现是有关的，说明你分析得有误。

**Comment by abusemydnac** [comment]
token 在old里面实现已经很清楚了,
后面碰见 ewxshinfo 才是绝望,  [ewxshinfo 是有时效的 大概五分钟]
由微信授权返回的code 参数页面, 生成的 ewxshinfo信息.
而 code参数 不能模拟获取.  微信浏览器授权后301 返回的,没机会模拟.
死循环.....    作者解决了这个问题 确实厉害.
--------------------------------------------------
现在就两个假想.  
1.ewxshinfo 解密后厘米有 用户openid 和 时间戳.  然后修改时间戳 重新加密.服务器验证通过.
2. 模拟获取 微信授权code. 但是看了官方文档.作者能在只有美团cookies,情况先实现不大可能吧.
------------------------------------------------
我已放弃.哈哈哈~

**Comment by JaonDong** [comment]
66666
