### ISSUE TITLE
这算bug吗

### ISSUE THREAD

**Issue by ZManor** [mtdhb/mtdhb#108]
饿了么有额度，领一次减一次，却领不成功，但的确又有小号去占位了

![20180524_112114](https://user-images.githubusercontent.com/5259526/40463005-3b51ca6a-5f45-11e8-863c-5794a308c70f.png)

**Comment by 605666069** [comment]
你次数不够就领不了呗，建议去看下规则

**Comment by ZManor** [comment]
明白了，这个次的概念有点歧义。那就是说要领一个红包通常要2个cookie，第二天回满是到5次还是10次？

**Comment by zhuweiyou** [comment]
领取的页面第一句话：请先阅读规则之后再来领取
