### ISSUE TITLE
比较好奇，领红包的次数是怎么实现的。

### ISSUE THREAD

**Issue by zhangbufan** [mtdhb/mtdhb#110]
比如我找了个红包链接 随便改了链接里的lucky_number，网站也能正确的识别红包。非常好奇这个到底是怎么探测的，第一次抢完红包，或者抢红包的过程中有哪个返回值可以显示出真的的最大包是哪一个吗？

**Comment by zhuweiyou** [comment]
在 mtdhb/old 中，是以 lucky_number 作为最大红包索引的。
在新版的逻辑中，已经不看这个值了。

**Comment by zhangbufan** [comment]
能简单说下怎么判断的吗？我抓了饿了么返回的包数据，没有相关的标识。比较好奇是怎么搞的

**Comment by zhuweiyou** [comment]
某个接口是有返回的，具体你自己研究一下吧

**Comment by zhangbufan** [comment]
给点提示吧 大佬、、、

**Comment by zhangbufan** [comment]
找到了，感谢大佬
