### ISSUE TITLE
后端API调用问题

### ISSUE THREAD

**Issue by MAYBreath** [mtdhb/mtdhb#115]
我看了那个www的源码，后端api不可以直接调用吗？ 
比如用户登录接口
https://api.mtdhb.com/user/login

不能网站直接打开这样调用吗
https://api.mtdhb.com/user/login?account=abc&password=1234567

为什么直接返回错误
{"code":500,"message":"Internal Server Error","data":null}

**Comment by huangdenghe** [comment]
登录接口要 POST 请求
