### ISSUE TITLE
贡献饿了么 Cookie(QQ)

### ISSUE THREAD

**Issue by songshijun007** [mtdhb/mtdhb#116]
在提取cookie的时候，出现下面内容，找不到cookie
此浏览器功能专供开发者使用。请不要在此粘贴执行任何内容，这可能导致其他人收集获取您的账户信息（手机号、常用地址等），给您带来损失！

**Comment by zhuweiyou** [comment]
在这些内容的最下面 点击空白处 可以输入内容 `document.cookie`

**Comment by songshijun007** [comment]
@zhuweiyou 哦哦，谢谢啦
