### ISSUE TITLE
删除仓库

### ISSUE THREAD

**Issue by 1097919195** [mtdhb/mtdhb#117]
你们的仓库怎么跑到我这里来了啊，主页上有，我想删了，但是没有setting，看着比较难受，有点强迫症，求解决
![image](https://user-images.githubusercontent.com/17583103/41282489-c272139e-6e66-11e8-86b2-0a902b98a215.png)

**Comment by zhuweiyou** [comment]
...老哥, 这跟我们有什么关系

你应该找 github 反馈
