### ISSUE TITLE
登录不了，network error

### ISSUE THREAD

**Issue by niu666666** [mtdhb/mtdhb#118]
最近不小心退出了登录，好几天了都登不上去了

**Comment by skyflym** [comment]
我也是, 360极速浏览器, User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 , 
OPTIONS https://api.mtdhb.com/notice.json net::ERR_CONNECTION_TIMED_OUT
OPTIONS https://api.mtdhb.com/user/login net::ERR_CONNECTION_TIMED_OUT

**Comment by zhuweiyou** [comment]
https://github.com/mtdhb/mtdhb/issues/67

**Comment by zhuweiyou** [comment]
现在可以再试试了。

**Comment by zhuweiyou** [comment]
已处理
