### ISSUE TITLE
大红包被别人领走了，什么鬼！

### ISSUE THREAD

**Issue by fjfqhwk** [mtdhb/mtdhb#119]
![image](https://user-images.githubusercontent.com/34731269/42010004-5dd419ea-7abf-11e8-8f80-e100d3e987c9.png)
大红包被别人领走了，什么鬼的bug

**Comment by zhuweiyou** [comment]
不用点进去看，帮你领的都是小号微信。
要看饿了么APP账号里是否到账。
另一个是现在拼手气的地区很少了，基本都是品质联盟红包。

**Comment by fjfqhwk** [comment]
就是没有到账，所以才说的

**Comment by zhuweiyou** [comment]
看下 在不在 品质联盟里面。

**Comment by zhuweiyou** [comment]
![image](https://user-images.githubusercontent.com/8413791/42010162-f7a75780-7abf-11e8-9ba3-b610cc0d49c9.png)

**Comment by fjfqhwk** [comment]
不在，
![image](https://user-images.githubusercontent.com/34731269/42010159-f5163bf8-7abf-11e8-855b-5ed13f388a8b.png)
问题yin应该是：点击去看，结果占了一个名额，然后，程序没有计算出来，领的过程中，就被小号领了

**Comment by zhuweiyou** [comment]
你这提示 是没领成功呀。领成功是绿色的字

**Comment by fjfqhwk** [comment]
我知道，实际上3000ms timeout的时候是已经领取了完成了，只不过这个红包被点了一次，机会不够。最终导致要领取的账号没有领取到红包

**Comment by zhuweiyou** [comment]
懂你的意思，前面领取操作的时候已经领到最佳前一个了。
然后你再领了一次，刚好用小号把最大的领了。

**Comment by fjfqhwk** [comment]
对，就是timeout 显示出来时候，实际是领取过程中，穿插了一次动作我的主动领取动作，然后导致小号吧大红包领取了

**Comment by zhuweiyou** [comment]
主动领取？？就算没有 timeout 
你自己点进去的话，你没法领最大了，一个链接一个号码只能领一个红包的。

**Comment by fjfqhwk** [comment]
![image](https://user-images.githubusercontent.com/34731269/42010412-18884a9e-7ac1-11e8-8afb-aa7027fa8dd9.png)
![image](https://user-images.githubusercontent.com/34731269/42010435-2ca56a16-7ac1-11e8-9116-4a961c055fb3.png)

你看一下领取时间顺序就知道了，第6个领取的是大红包

**Comment by fjfqhwk** [comment]
我是看到显示timeout的，然后又试了一遍，然后才手动点击去看红包的
![image](https://user-images.githubusercontent.com/34731269/42010474-578011a0-7ac1-11e8-8f96-dada7e20ce94.png)

**Comment by fjfqhwk** [comment]
所以问题是，第一次领取的时候，虽然显示timeout，但是实际在领取过程中；
然后第二次我再次使用领取功能的时候，这次小号又开始领取了红包；而程序上一次动作还没有领完，这次的插入领取动作，导致了中间红包被小号领取了，而这次领取红包的小号是第二次领取的小号。

**Comment by fjfqhwk** [comment]
根据时间点看，还有更怪的问题，红包怎么会是第5个领取了大红包，而不是第6个

**Comment by zhuweiyou** [comment]
从领取时间看，就是 第一次领取的时候，领到最佳前一个。然后 timeout  了。
当你点第二次的时候，因为我们会先用小号去探测剩余数量的。所以会被误领掉。

![image](https://user-images.githubusercontent.com/8413791/42010580-f296433a-7ac1-11e8-97c0-359842ee718c.png)

**Comment by fjfqhwk** [comment]
也有可能是前两个，总的来说就是领取一半timeout了
![image](https://user-images.githubusercontent.com/34731269/42010639-2baf3a3c-7ac2-11e8-9075-d70a866f7b80.png)
