### ISSUE TITLE
领取次数问题

### ISSUE THREAD

**Issue by RRyn** [mtdhb/mtdhb#120]
才领取了一个最佳红包，但是次数直接从5/5次 变成了0/5次？这是为何吗

**Comment by huangdenghe** [comment]
请先阅读规则

**Comment by RRyn** [comment]
那这样的话 比如我贡献了1个cookie，但是第七个才是最大的话 我就可能领取不到最佳红包了? @huangdenghe  
除了在贡献cookie没有别的办法了么
