### ISSUE TITLE
mac 微信打开链接必须在微信浏览器

### ISSUE THREAD

**Issue by AkiraSun** [mtdhb/mtdhb#122]
mac 微信打开链接必须在微信浏览器，必须让我授权登陆微信，登陆以后就自动领取了，不能拿到原始的链接
![image](https://user-images.githubusercontent.com/21287041/42722773-8c7174f6-8784-11e8-98fb-50cf903696f4.png)
微信版本号mac 2.3.17.18

**Comment by zhuweiyou** [comment]
使用自带浏览器打开，复制地址栏

**Comment by WangChangQin** [comment]
Mac拿Charles拿到的美团Cookie好像不能用

**Comment by zhuweiyou** [comment]
@WangChangQin 网页上已经说明了，美团新 cookie 已失效，只有部分老用户的号还能用。

**Comment by WangChangQin** [comment]
@zhuweiyou  这样啊，谢谢～
