### ISSUE TITLE
无法注册,验证码输入正确,提示输入正确验证码.

### ISSUE THREAD

**Issue by huohongxu** [mtdhb/mtdhb#125]

**Comment by fruittt** [comment]
用手机打开注册试一下

**Comment by huohongxu** [comment]
试了,还是提示输入正确验证码,但是验证码确实为正确的

**Comment by fruittt** [comment]
你发给我邮箱地址帮你注册吧。664463976@qq.com

**Comment by huangdenghe** [comment]
@huohongxu 请告知我们所使用的浏览器，以便我们可以复现问题

**Comment by huangdenghe** [comment]
@fruittt 帮忙测试一些海外线路是不是没有这个问题，网页上有个线路切换的下拉框可以选择线路。谢谢

**Comment by fruittt** [comment]
@huangdenghe 海外路线正常，换成Chrome也没有问题
