### ISSUE TITLE
小号贡献cookie提示 已存在

### ISSUE THREAD

**Issue by weicracker** [mtdhb/mtdhb#126]
第一天使用小号贡献一个cookie 可使用次数增加为5，但是没有领红包，没有使用可用次数，次数还为5

第二天再贡献原小号 新产生的第二天的cookie ，  提示cookie已存在 无法贡献 cookie

**Comment by huangdenghe** [comment]
一个小号对应一个 cookie

**Comment by weicracker** [comment]
第二天剩余可消耗次数会自动回满对吗

**Comment by huangdenghe** [comment]
对

**Comment by weicracker** [comment]
谢谢你，知道了~
