### ISSUE TITLE
领取问题

### ISSUE THREAD

**Issue by marrrrk5** [mtdhb/mtdhb#127]
昨天领取时什么都没有提示，也没有领取成功，现在再次输入连接的时候会提示该链接以领取或正在领取中
，请换一个红包连接再来

**Comment by huangdenghe** [comment]
@marrrrk5 你的上一条回复说明内容都没

**Comment by huangdenghe** [comment]
我还是没明白你在说的是什么问题，我查了数据库没有未领取完成的记录
