### ISSUE TITLE
领取遇到的bug

### ISSUE THREAD

**Issue by duanxianwp** [mtdhb/mtdhb#132]
事情是这样的。
有一个饿了么红包，是第6个是大红包，我用一个号领，然后突然告诉我这个手机号领上限了。
我又换了另一个号领，告诉我大红包已经被领取了，查看了下手气最佳的不是我认识的，是僵尸号领的。
然后我就啥都没有了。。。。

**Comment by zhuweiyou** [comment]
提示领上限了，此时已经领到第 5 个了。
如果你再换一个号用网站领的话，第一个红包是会被机器人领掉的。
> 正确的做法是，提示到上限了之后，用手机手动去点红包就是最大。

**Comment by duanxianwp** [comment]
好吧，我并没有仔细阅读相关提示，打扰了。
