### ISSUE TITLE
饿了么领取代码问题

### ISSUE THREAD

**Issue by mljxxx** [mtdhb/mtdhb#133]
为什么有时候饿了么红包领取时那个put之后领取的还不是自己的号码,我测试下应该是那个put的问题，然而我没有捕获到异常，状态码都是204,而且那个号码也是注册了饿了么的，但就是没成功绑定，也尝试过绑定两次依然不行。。。

**Comment by zhuweiyou** [comment]
下一个接口的 ret_code 是几？

**Comment by mljxxx** [comment]
领取成功是4,不过那个account和我要绑定的号码不一样

**Comment by zhuweiyou** [comment]
这个情况是绑定大号，还是代领小号？
使用的我们的 mtdhb/get 代码，还是自己写的？

**Comment by mljxxx** [comment]
是这个情况，我自己写的，主要是它为什么没绑定成功，没成功还没有什么返回和异常

**Comment by zhuweiyou** [comment]
那个请求没返回值的，你把代码粘贴出来我看看，有可能漏了什么。

**Comment by mljxxx** [comment]
`def fun(sn,lucky_number,phone,index,nickname):
    # print(phone)
    headers = {'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; PRO 6 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043221 Safari/537.36 V1_AND_SQ_7.0.0_676_YYB_D QQ/7.0.0.3135 NetType/WIFI WebP/0.3.0 Pixel/1080'}

    res=requests.put(url='https://h5.ele.me'+'/restapi/v1/weixin/'+cookie[index]['openid']+'/phone',headers=headers,data=json.dumps({
                      'sign': cookie[index]['eleme_key'],
                      'phone':phone
                  }))

    data=json.dumps({
        'device_id': '',
        'group_sn': sn,
        'hardware_id': '',
        'method': 'phone',
         'phone':phone,
         'platform':'',
         'sign' : cookie[index]['eleme_key'],
        'track_id': '',
        'unionid': 'fuck',
        'weixin_avatar': '',
        'weixin_username': nickname
    })

    res=requests.post(url='https://h5.ele.me/restapi/marketing/promotion/weixin/'+cookie[index]['openid'],headers=headers,data=data).json()
   return res`
这个是领取一个的代码，如果只剩一个会传入指定的phone但是可能没绑定成功

**Comment by zhuweiyou** [comment]
没看出什么毛病，加下 452599197 Q 群交流，在这里讨论太慢了。

**Comment by zhuweiyou** [comment]
最终是缺少 header 解决了吧？
