### ISSUE TITLE
关于粮票和品质联盟大红包的叠加

### ISSUE THREAD

**Issue by Darker2** [mtdhb/mtdhb#136]
贵团队：
    首先感谢贵团队的付出。
    在使用淘宝>>饿了么途径下单时，可以粮票和饿了么大红包叠加使用，但是此订单好像不能生成饿了么大红包领取链接了。以前的大红包都是用一个然后用订单领一个，现在断档了怎么破。。

以上
谢谢

**Comment by iola1999** [comment]
246080018 交流群 1。群内有机器人免费发送大量品质联盟大包。

**Comment by zhuweiyou** [comment]
让你朋友分享给你，或者加几个外卖群弄红包。
另外，王老吉活动貌似已经结束了？

**Comment by wardenlzr** [comment]
王老吉活动前天就结束了吧
