### ISSUE TITLE
大佬，短网址咋解析出来？

### ISSUE THREAD

**Issue by wxungang** [mtdhb/mtdhb#137]

**Comment by zhuweiyou** [comment]
用 GET 请求拿 response.headers['location']

**Comment by zhuweiyou** [comment]
代码可参考这里

https://github.com/mtdhb/api/blob/0c45b530297ce7489eaa75f44319cf2809aa9196/src/main/java/com/mtdhb/api/util/Connections.java#L33-L47

**Comment by wxungang** [comment]
已搞定！谢谢大佬！前端小菜鸟一个，看不太懂 java. 谢谢了
