### ISSUE TITLE
api 部署 nginx配置能不能给个

### ISSUE THREAD

**Issue by 362024758** [mtdhb/mtdhb#138]
部署api访问不了。。。

**Comment by zhuweiyou** [comment]
具体错误呢？

**Comment by 362024758** [comment]
申请账号页面 注册码 出不来  
点 申请 会出现 Network Error 是什么问题

**Comment by zhuweiyou** [comment]
打开浏览器开发者工具 看下 network 是 404 还是跨域？

**Comment by 362024758** [comment]
好像不是404 
xhr.js:178 OPTIONS https://api.mtdhb.com/user/registerMail 0 ()
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:57
Promise.then (async)
n.request @ Axios.js:51
n.(anonymous function) @ Axios.js:71
(anonymous) @ bind.js:9
e.getRegisterCode @ Apply.js:26
e.handleSubmit @ Apply.js:52
r @ react-dom.min.js:14
a @ react-dom.min.js:12
s @ react-dom.min.js:12
f @ react-dom.min.js:12
m @ react-dom.min.js:12
r @ react-dom.min.js:15
processEventQueue @ react-dom.min.js:12
r @ react-dom.min.js:14
handleTopLevel @ react-dom.min.js:14
i @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
dispatchEvent @ react-dom.min.js:14
api.mtdhb.com/user/registerCaptcha?1536721315376:1 GET https://api.mtdhb.com/user/registerCaptcha?1536721315376 0 ()
Image (async)
e.changeCaptcha @ Apply.js:85
(anonymous) @ Apply.js:42
Promise.catch (async)
e.getRegisterCode @ Apply.js:40
e.handleSubmit @ Apply.js:52
r @ react-dom.min.js:14
a @ react-dom.min.js:12
s @ react-dom.min.js:12
f @ react-dom.min.js:12
m @ react-dom.min.js:12
r @ react-dom.min.js:15
processEventQueue @ react-dom.min.js:12
r @ react-dom.min.js:14
handleTopLevel @ react-dom.min.js:14
i @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
dispatchEvent @ react-dom.min.js:14
xhr.js:178 OPTIONS https://api.mtdhb.com/user/registerMail 0 ()
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:57
Promise.then (async)
n.request @ Axios.js:51
n.(anonymous function) @ Axios.js:71
(anonymous) @ bind.js:9
e.getRegisterCode @ Apply.js:26
e.handleSubmit @ Apply.js:52
r @ react-dom.min.js:14
a @ react-dom.min.js:12
s @ react-dom.min.js:12
f @ react-dom.min.js:12
m @ react-dom.min.js:12
r @ react-dom.min.js:15
processEventQueue @ react-dom.min.js:12
r @ react-dom.min.js:14
handleTopLevel @ react-dom.min.js:14
i @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
dispatchEvent @ react-dom.min.js:14
api.mtdhb.com/user/registerCaptcha?1536721318036:1 GET https://api.mtdhb.com/user/registerCaptcha?1536721318036 0 ()
Image (async)
e.changeCaptcha @ Apply.js:85
(anonymous) @ Apply.js:42
Promise.catch (async)
e.getRegisterCode @ Apply.js:40
e.handleSubmit @ Apply.js:52
r @ react-dom.min.js:14
a @ react-dom.min.js:12
s @ react-dom.min.js:12
f @ react-dom.min.js:12
m @ react-dom.min.js:12
r @ react-dom.min.js:15
processEventQueue @ react-dom.min.js:12
r @ react-dom.min.js:14
handleTopLevel @ react-dom.min.js:14
i @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
dispatchEvent @ react-dom.min.js:14
xhr.js:178 OPTIONS https://api.mtdhb.com/user/registerMail 0 ()
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:57
Promise.then (async)
n.request @ Axios.js:51
n.(anonymous function) @ Axios.js:71
(anonymous) @ bind.js:9
e.getRegisterCode @ Apply.js:26
e.handleSubmit @ Apply.js:52
r @ react-dom.min.js:14
a @ react-dom.min.js:12
s @ react-dom.min.js:12
f @ react-dom.min.js:12
m @ react-dom.min.js:12
r @ react-dom.min.js:15
processEventQueue @ react-dom.min.js:12
r @ react-dom.min.js:14
handleTopLevel @ react-dom.min.js:14
i @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
dispatchEvent @ react-dom.min.js:14
api.mtdhb.com/user/registerCaptcha?1536721319232:1 GET https://api.mtdhb.com/user/registerCaptcha?1536721319232 0 ()
Image (async)
e.changeCaptcha @ Apply.js:85
(anonymous) @ Apply.js:42
Promise.catch (async)
e.getRegisterCode @ Apply.js:40
e.handleSubmit @ Apply.js:52
r @ react-dom.min.js:14
a @ react-dom.min.js:12
s @ react-dom.min.js:12
f @ react-dom.min.js:12
m @ react-dom.min.js:12
r @ react-dom.min.js:15
processEventQueue @ react-dom.min.js:12
r @ react-dom.min.js:14
handleTopLevel @ react-dom.min.js:14
i @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
dispatchEvent @ react-dom.min.js:14
xhr.js:178 OPTIONS https://api.mtdhb.com/user/registerMail 0 ()
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:57
Promise.then (async)
n.request @ Axios.js:51
n.(anonymous function) @ Axios.js:71
(anonymous) @ bind.js:9
e.getRegisterCode @ Apply.js:26
e.handleSubmit @ Apply.js:52
r @ react-dom.min.js:14
a @ react-dom.min.js:12
s @ react-dom.min.js:12
f @ react-dom.min.js:12
m @ react-dom.min.js:12
r @ react-dom.min.js:15
processEventQueue @ react-dom.min.js:12
r @ react-dom.min.js:14
handleTopLevel @ react-dom.min.js:14
i @ react-dom.min.js:14
perform @ react-dom.min.js:15
batchedUpdates @ react-dom.min.js:14
i @ react-dom.min.js:14
dispatchEvent @ react-dom.min.js:14
api.mtdhb.com/user/registerCaptcha?1536721324859:1 GET https://api.mtdhb.com/user/registerCaptcha?1536721324859 0 ()

**Comment by zhuweiyou** [comment]
你现在请求的还是 api.mtdhb.com 要换成你自己的域名
在 src/api/domain 里面

**Comment by 362024758** [comment]
我是本地hosts 文件 ip绑定了这个域名 这样也可以吧？

**Comment by zhuweiyou** [comment]
你能截图吗，你这发的错误，判断不出来。
nginx 遇到 options 请求返回 204 这个加了没

**Comment by 362024758** [comment]
再试试看 谢谢啊

**Comment by Mydrn** [comment]
我的是配置好了 502 启动也是正常的 改了端口也不行
