### ISSUE TITLE
这是跨域问题吗

### ISSUE THREAD

**Issue by 362024758** [mtdhb/mtdhb#139]
createError.js:16 Uncaught (in promise) Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.h.onerror (xhr.js:87)

Failed to load http://api.mtdhb.com/user/registerMail: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains the invalid value '0'. Origin 'http://192.168.24.131:5000' is therefore not allowed access.
![clipboard](https://user-images.githubusercontent.com/32425987/45412024-53b60980-b6a8-11e8-9f82-94fe7cb7a913.png)

![clipboard11](https://user-images.githubusercontent.com/32425987/45412133-87912f00-b6a8-11e8-99fa-ef04a2c7948a.png)

验证码可以生成出来

申请会弹出 network error
没办法注册
这是跨域问题吗

**Comment by zhuweiyou** [comment]
对。在nginx里加入 http://192.168.24.131:5000 的白名单。或者直接设置成 * 号（有安全风险）

**Comment by 362024758** [comment]
![image](https://user-images.githubusercontent.com/32425987/45417737-74d12700-b6b5-11e8-8dba-199586bf2d1a.png)
![image](https://user-images.githubusercontent.com/32425987/45417770-8286ac80-b6b5-11e8-9563-5656c29f284e.png)

邮件有收到 还是有个问题  但是激活网址这里怎么设置的 跳转注册账号呢

**Comment by zhuweiyou** [comment]
api 里面有 邮件模板。 可以修改地址

**Comment by 362024758** [comment]
![image](https://user-images.githubusercontent.com/32425987/45471707-81608880-b764-11e8-8eaf-2dea0b41bebd.png)

![image](https://user-images.githubusercontent.com/32425987/45471691-74439980-b764-11e8-8a1b-c571a055fbb1.png)

自己部署的 没办法贡献cookie 吗

**Comment by zhuweiyou** [comment]
饿了么这几天改版了哦，你要重新去抓接口分析。

**Comment by zhuweiyou** [comment]
新版已经可以了
