### ISSUE TITLE
大佬，注册界面验证码加载不出来是什么原因呀

### ISSUE THREAD

**Issue by tiancai110** [mtdhb/mtdhb#140]

**Comment by zhuweiyou** [comment]
具体错误发一下。network 截图

**Comment by tiancai110** [comment]
![qq 20180918102836](https://user-images.githubusercontent.com/39119944/45661934-4a0e2500-bb32-11e8-97bf-55a47f575762.jpg)

**Comment by tiancai110** [comment]
没看到报错的地方

**Comment by zhuweiyou** [comment]
Console 有报错吗。

**Comment by Mydrn** [comment]
![image](https://user-images.githubusercontent.com/28941224/49564281-f0154280-f95d-11e8-90e9-b2506061f770.png)
我的也是不行 接口502 改端口启动 还是这样

**Comment by zhuweiyou** [comment]
这是服务端挂了，才 502

**Comment by Mydrn** [comment]
> 这是服务端挂了，才 502
是我api boot项目没部署 
我还以为api 也集成在docker里面
请问docker用本地的mysql怎么修改 只要注释image 其他改成本地就行了吗

**Comment by zhuweiyou** [comment]
@Mydrn  docker 带有 api 这块的。如果你不用 docker 你就别看这个，直接分别部署 mtdhb/api 和 mtdhb/get

**Comment by Mydrn** [comment]
![image](https://user-images.githubusercontent.com/28941224/49567400-8d757400-f968-11e8-8ab1-42301132c6e1.png)
我之前用docker启动 api的就502 但启动好了不知道为啥 所以我才去下boot api

**Comment by zhuweiyou** [comment]
> 我之前用docker启动 api的就502 但启动好了不知道为啥 所以我才去下boot api

看日志呀

**Comment by Mydrn** [comment]
日志是空的

**Comment by zhuweiyou** [comment]
> 日志是空的

如果你是 prod 模式启动，要在 `系统临时目录/log/api` 这里看日志

**Comment by Mydrn** [comment]
![image](https://user-images.githubusercontent.com/28941224/49567859-f01b3f80-f969-11e8-96cf-d6b126c98581.png)
里面没有 很无语了

**Comment by Mydrn** [comment]
> > 日志是空的
> 
> 如果你是 prod 模式启动，要在 `系统临时目录/api/log` 这里看日志

就是用 run.sh 启动 都没日志

**Comment by zhuweiyou** [comment]
问题是否解决？
