### ISSUE TITLE
【反馈一下】出现剩余次数为-1的情况

### ISSUE THREAD

**Issue by wuyude** [mtdhb/mtdhb#141]
在饿了么剩余次数为8时，领第9个为最大的红包，未填手机号，之后最大红包被领取，剩余次数变为-1。虽然感觉无伤大雅，但还是来反馈一下吧。附截图。
![snipaste_2018-09-27_23-20-49](https://user-images.githubusercontent.com/38122505/46156697-a1d42b00-c2ac-11e8-9606-43792184a66c.png)

**Comment by zhuweiyou** [comment]
放假没有看 issue，现在我们允许这种负数的情况发生，忽略它就好。
比如今天你用的次数比较多，而 cookie 又有失效的，当天也可能产生负的。
