### ISSUE TITLE
应该可以实现自动领取最大的红包的功能吧

### ISSUE THREAD

**Issue by ddquk** [mtdhb/mtdhb#142]
而且目前的情况，第五个最大，如果领取到第四个了发给网站，是会被小号领取的，在目前使用人数足够多的情况下，应该可以先判断出当前红包还有多少个到最大吧？有没有相关的API可以用的

**Comment by zhuweiyou** [comment]
![image](https://user-images.githubusercontent.com/8413791/46213460-356c3100-c36b-11e8-8cae-22ec23de94fa.png)

你都领到第 4 了，还用网站干什么。直接点不就行了。
