### ISSUE TITLE
登录进去后请求api接口全是500错错

### ISSUE THREAD

**Issue by dcsunny** [mtdhb/mtdhb#149]
`
Request URL: http://api.hongbao.com/user/cookie
Request Method: GET
Status Code: 500 
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-User-Token,Auth-Origin,Origin,X-Auth-Token,Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS, TRACE
Access-Control-Allow-Origin: http://localhost:4001
Access-Control-Max-Age: 2592000
Connection: keep-alive
Content-Length: 21
Content-Type: application/json;charset=UTF-8
Date: Thu, 18 Oct 2018 07:19:44 GMT
Server: nginx/1.13.12
Provisional headers are shown
Accept: application/json, text/plain, */*
Origin: http://localhost:4001
Referer: http://localhost:4001/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
X-User-Token: EA84CCD145C970EA2F101E76DAD0E54C59A43718F0E1F097952460BA15AFB9A58938F45CB3F7A8520ED3C98EDA770A446A5A2E58877C322CFF2B709F91AB488A
`
结果都是 Internal Server Error

**Comment by zhuweiyou** [comment]
500 是 API 端报错了，可以查看相关的日志。

**Comment by dcsunny** [comment]
嗯嗯，docker-compose的redis没有加入networks:- net-spring-db 导致连接不上redis

**Comment by fulln** [comment]
> 嗯嗯，docker-compose的redis没有加入networks:- net-spring-db 导致连接不上redis

 你加去后能连了？  你是使用的自己build的还是直接run的
