### ISSUE TITLE
美团红包分享链接优化

### ISSUE THREAD

**Issue by Gitxio** [mtdhb/mtdhb#161]
现在美团红包分享链接不是原来的链接，而是变成短链接，每次领红包都要先打开短链跳转到领红包的界面复制网址，很麻烦，希望早日优化

**Comment by zhuweiyou** [comment]
不知道你说的短链接是什么样子的，能否给个示例？
我们是支持 url.cn 的短链的。

**Comment by Gitxio** [comment]
http://dpurl.cn/UV88rLn

**Comment by zhuweiyou** [comment]
已记录，有空会优化一下。

**Comment by zhuweiyou** [comment]
晚一点服务会更新，就支持了。
