### ISSUE TITLE
大家注意一下，是贡献小号的cookies

### ISSUE THREAD

**Issue by yihleego** [mtdhb/mtdhb#6]
cookies其实是个挺敏感的东西，别人有了这个不用帐号密码就可以登录你的号，所以大家贡献的话**用小号**，**别贡献自己用的账号**。

申请小号去了 :V

**Comment by zhuweiyou** [comment]
> 别人有了这个不用帐号密码就可以登录你的号

嗯，你说得对，但又不完全。

只是 **登录 cookie 对应的网站**，而不是登录微信号或者 QQ 号。

**Comment by yihleego** [comment]
嗯，就是希望大家注意一下，不然到时候把自己的号放上去了，让管理员删除记录什么的有点麻烦。

**Comment by MAYBreath** [comment]
是的 这个cookie是比较敏感的数据，如果是我设计的话 一般只要有cookie ，是基本等于有了饿了么账号密码的权限。可以下单 或者评论 应该都是可以的。
这边要说的是不要轻易给别人，要给也是要给小号，楼上说的委婉了，不是 删除记录麻烦的事，是安全问题。

**Comment by zhuweiyou** [comment]
@MAYBreath  

如果对于一般的网站来说，你说的是对的。

但对美团、饿了么的抢红包页面，是不需要用账号登录的。

**实际上并不会拥有饿了么账号密码权限。**

我举个例子，我有一个微信号，进去填你的手机号码绑定，我肯定不能拥有你的账号控制权。

**Comment by zhuweiyou** [comment]
@yihleego  现在领取和删除功能都已经上线啦

**Comment by MAYBreath** [comment]
嗯 我知道的。。我是说我设计的话。。
这个只是领红包的cookie，不是饿了么账号的token。我就是提醒下这个cookie和token的安全性。
因为我本身也很懒，如果我要校验饿了么账号的话 cookie肯定会和token设置相同的用户id，但是这个红包本身没有和饿了么绑定，所以没事的。。。

**Comment by gyx99** [comment]
其实小号的话直接给账号密码省事也是愿意的
