### ISSUE TITLE
[Feture]建议增加自定义领取次数

### ISSUE THREAD

**Issue by fifteenzhang** [mtdhb/mtdhb#74]
eg: 现有cookies可领13次，
      红包最大7个，
用户可以自定义领取个数为6个，这样可以存红包以备用。
也可以避免出现红包最大6个，自己cookie只能领5次，从而领不了的情况。毕竟理论上来说只需要小号点5次就好了。

**Comment by zhuweiyou** [comment]
我们考虑出：不填手机号领到最佳前一个的功能。

此时不做不足判断

**Comment by zhuweiyou** [comment]
已支持
