### ISSUE TITLE
领取红包账号非填写帐号

### ISSUE THREAD

**Issue by zx3254** [mtdhb/mtdhb#78]
红包地址
https://activity.waimai.meituan.com/coupon/sharechannel/B2EA8E1ABA8B47EA82DB475BA17B517D?urlKey=AD8D5636848C492C9A1DC218C3D74F38

领取账号
17714329204

实际领取账号非 17714329204

**Comment by zhuweiyou** [comment]
美团确实存在这个情况，请参考这边的回复 https://github.com/game-helper/hongbao2/issues/71

**Comment by zhuweiyou** [comment]
https://github.com/mtdhb/www/commit/bf27b4c1eb6d25b084d1bd7b5f9aa8d854ff2b04 支持领取到最佳前一个 一定程度解决这个问题
