### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by 627433** [mtdhb/mtdhb#81]
Failed to load https://api.mtdhb.com/user/resetPassword: The 'Access-Control-Allow-Origin' header contains multiple values 'https://www.mtdhb.com, *', but only one is allowed. Origin 'https://www.mtdhb.com' is therefore not allowed access.

这是什么问题呢

**Comment by huangdenghe** [comment]
什么情况产生的错误？操作系统？浏览器和版本？是我们线上环境吗？还是用我们开源的前端代码自己本地跑的？

**Comment by zhuweiyou** [comment]
目前 API 不支持除白名单外的跨域调用

如果你是自己搭网站的话，请自行反向代理 api 域名。

如果是使用我们网站的过程中出现的问题，请提供楼上问的更详细的信息，便于我们排查问题。

**Comment by zhuweiyou** [comment]
此 issue 时间过长无反馈，先关闭了。
