### ISSUE TITLE
美团提示领取成功但是被其他账号领取了

### ISSUE THREAD

**Issue by turtlejk** [mtdhb/mtdhb#82]
链接:https://activity.waimai.meituan.com/coupon/sharechannel/B2EA8E1ABA8B47EA82DB475BA17B517D?urlKey=FFEEB442A6FB4508BDD9D6EE34AF7861

账号是turtlejk@hotmail.com
手机号是13728785284
我再用自己的手机号进去是领大红包下面一个了

**Comment by huangdenghe** [comment]
打开美团 App 看过了吗

**Comment by turtlejk** [comment]
看过了,领的时候就一直开着
后来也重新打开看过
App里的红包是后面我自己点进去领的大红包下面那个小红包

**Comment by zhuweiyou** [comment]
美团确实有可能出现你说的问题。
我们已经记录了，会做一下优化。

**Comment by zhuweiyou** [comment]
https://github.com/mtdhb/www/commit/bf27b4c1eb6d25b084d1bd7b5f9aa8d854ff2b04 支持领取到最佳前一个

**Comment by zhuweiyou** [comment]
https://github.com/mtdhb/www/commit/bf27b4c1eb6d25b084d1bd7b5f9aa8d854ff2b04 支持领取到最佳前一个
