### ISSUE TITLE
兄弟，我的想法和你一样，原来你已经开始做了

### ISSUE THREAD

**Issue by JaonDong** [mtdhb/mtdhb#88]
我也想到了，使用微信公众号或者微信小程序做红包最佳。等等以后的场景

**Comment by zhuweiyou** [comment]
小程序之前做过一版，被拒了。就没继续 https://github.com/game-helper/hongbao

**Comment by zhuweiyou** [comment]
小程序已开发了，公众号以后再看要不要做。

**Comment by zhuweiyou** [comment]
此 issue 时间过长，先关闭了
