### ISSUE TITLE
美团红包领取错误

### ISSUE THREAD

**Issue by zhaochuang** [mtdhb/mtdhb#93]
显示领取成功，实际却是其他人领取的。
不知道这个bug解决了吗？我今天又遇到这种情况了

**Comment by zhuweiyou** [comment]
https://github.com/game-helper/hongbao2/issues/71

这个问题仍然存在的。

是由于美团返回的领取列表，有时候不是最新的。

导致程序判断到还没到最佳，所以会被小号领掉。

后续我们会出一个领到最佳之前的功能，可以一定程度解决大包被误领的情况。

**Comment by zhuweiyou** [comment]
https://github.com/mtdhb/www/commit/bf27b4c1eb6d25b084d1bd7b5f9aa8d854ff2b04 支持领取到最佳前一个
