### ISSUE TITLE
弱弱问句后端啥时候开源啊

### ISSUE THREAD

**Issue by iddddg** [mtdhb/mtdhb#97]

**Comment by zhuweiyou** [comment]
等吧，着急可以参考旧版自己改改

**Comment by iddddg** [comment]
不着急不着急哈哈,自己抓包能找到美团和饿了么的领取,用php的curl也能领取到,就好奇你们咋写咋优化的23333.加油大佬们

**Comment by JaonDong** [comment]
你说的优化是哪方面优化？

**Comment by iddddg** [comment]
@JaonDong 也没啥,就是判断领取成功失败,循环啊之类的。领红包可以领到

**Comment by lovezm** [comment]
我能写出EXE 但是.没那么多COOKIE。。。

**Comment by Hvictory1** [comment]
我按照步骤来的可是qq获取的cookie特别短  然后贡献失败  是为什么

**Comment by huangdenghe** [comment]
所有代码已全部开源
